### ISSUE TITLE
Unused `redirects.yml`

### ISSUE THREAD

**Issue by igorwwwwwwwwwwwwwwwwwwww** [travis-ci/travis-redirect#2]
It seems to me like `redirects.yml` is not actually used in `config.ru`. It would be great if someone (@rkh?) could confirm that it can be removed. Since having it there unused would be confusing and misleading.

**Comment by rkh** [comment]
Confirm, it has been removed in 2091ff12f3fbec90e57ef911b48ec6933f603961.
